#!/bin/bash

keywords=("break" "default" "func" "interface" "select"
          "case" "defer" "go" "map" "struct"
          "chan" "else" "goto" "package" "switch"
          "const" "fallthrough" "if" "range" "type"
          "continue" "for" "import" "return" "var")

pokemon=("bulbasaur" "ditto" "flareon" "ivysaur" "snorlax" 
         "charmander" "diglett" "golduck" "meowth" "starmie"
         "chansey" "eevee" "goldeen" "pikachu" "slowpoke"
         "cloyster" "fearow" "jynx" "rattata" "tentacool" 
         "clefairy" "jigglypuff" "exeggutor" "exeggcute" "venusaur")

if [ "$#" -eq 3 ] && [ $1 == "convert" ] && [ -f $2 ]; then
    cp $2 $3
    for ((i=0;i<${#keywords[@]};++i))
    do
        sed -i ".bak" "s/${keywords[i]}/${pokemon[i]}/g" $3
    done
    rm $3.bak
elif [ "$#" -ne 2 ]; then
    go "$@" | sed s/go/pokemon-go/g
elif [ $1 != "run" ]; then
    go "$@" | sed s/go/pokemon-go/g
elif [ ! -f "$2" ]; then
    go "$@" | sed s/go/pokemon-go/g 
else
    cp $2 tmp_pokemon_go.go
    for ((i=0;i<${#keywords[@]};++i))	
    do
        sed -i ".bak"  "s/${pokemon[i]}/${keywords[i]}/g" tmp_pokemon_go.go
    done
    go run tmp_pokemon_go.go
    rm tmp_pokemon_go.go tmp_pokemon_go.go.bak
fi

